name: hooksman
description: Create git hooks and tasks using Dart scripts and Shell commands
version: 3.1.2
repository: https://github.com/mrgnhnt96/hooksman
issue_tracker: https://github.com/mrgnhnt96/hooksman/issues
funding:
  - https://github.com/sponsors/mrgnhnt96
topics:
  - git
  - hooks
  - git-hooks
  - shell
  - script

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  async: ^2.12.0
  change_case: ^2.1.0
  collection: ^1.19.1
  equatable: ^2.0.7
  file: ^7.0.1
  glob: ^2.1.2
  mason_logger: ^0.3.1
  meta: ^1.16.0
  scoped_deps: ^0.1.0+2
  uuid: ^4.5.1

dev_dependencies:
  build_runner: ^2.10.4
  equatable_gen: ^1.2.0
  mocktail: ^1.0.4
  test: ^1.25.11

executables:
  hooksman:
